services:
  nginx:
    image: tiangolo/nginx-rtmp:latest
    container_name: "nginx-rtmp"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - streams-volumes:/hls/live
    ports:
      - "1935:1935"
    depends_on:
      auth_server:
        condition: service_started

  playback_server:
    build:
      dockerfile: ./Dockerfile.playback
      context: .
    container_name: "playback-stream"
    ports:
      - "8001:8001"
    depends_on:
      - auth_server
      - nginx
    volumes:
      - streams-volumes:/hls/live

  auth_server:
    build:
      dockerfile: ./Dockerfile.auth
      context: .
    container_name: "stream-auth"
    ports:
      - "8000:8000"
    hostname: auth_server
    environment:
      POSTGRES_PASSWORD: "PASSOWRD123"
      POSTGRES_USER: postgres
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: "streamkeys"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:18
    container_name: "postgres-stream"
    restart: unless-stopped
    hostname: postgres
    volumes:
      - ./scripts/1_init.sql:/docker-entrypoint-initdb.d/1_init.sql
      - ./scripts/2_stream_keys_populate.sql:/docker-entrypoint-initdb.d/2_stream_keys_populate.sql
    environment:
      POSTGRES_PASSWORD: "PASSOWRD123"
      POSTGRES_DB: "streamkeys"
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 2s
      timeout: 2s
      retries: 5

volumes:
  streams-volumes:
